// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const list: string;
export const listItem: string;
export const listItemLink: string;
export const listItemDescription: string;
export const textCenter: string;
export const intro: string;
