// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const itemHidden: string;
export const wrapper: string;
export const topbar: string;
export const topbarLogo: string;
export const topbarContent: string;
export const topbarMain: string;
export const topbarButtons: string;
export const topbarItem: string;
export const sidebarContainer: string;
export const content: string;
export const contentLogo: string;
export const background: string;
export const icon: string;
