// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const h1Typography: string;
export const h2Typography: string;
export const h3Typography: string;
export const h4Typography: string;
export const pTypography: string;
export const itemHidden: string;
export const container: string;
