// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const containerRecipe: string;
export const containerHeader: string;
export const containerNutritionalValues: string;
export const containerDetails: string;
export const containerIngredients: string;
export const containerPreparation: string;
