export const exampleRecipe = {
  url: 'https://www.fitczarodziejka.pl/przepis/ciasto-na-pizze-z-tunczykiem',
  name: 'Ciasto na pizzę z tuńczykiem',
  ingredients: [
    ['1', 'puszka tuńczyka w wodzie'],
    ['2', 'białka jajek'],
    ['czosnek', 'granulowany'],
    ['pieprz'],
    ['dodatki', '(do smaku)'],
  ],
  nutritional_values: {
    calories: '122 Kcal',
    carbohydrates: '0 g',
    fiber: '0 g',
    protein: '27 g',
    fat: '1 g',
  },
  preparation_method: [
    'Wymieszaj odsączonego tuńczyka z białkami jaj i przyprawami.',
    'Przełóż masę na blaszkę wyłożoną papierem do pieczenia.',
    'Piecz ciasto w 190 stopniach przez 10 minut.',
    'Następnie połóż wybrane składniki na cieście i piecz przez kolejne 5 minut.',
  ],
  tags: [
    'Bez cukru',
    'Niskokaloryczne',
    'Przepisy na obiad i lunch',
    'Bezglutenowe',
    'Bez dodatku orzechów',
    'Tuńczyk',
    'Przepisy na lunch i obiad bez nabiału',
    'Przepisy z tuńczykiem na lunch i obiad',
    'Niskokaloryczne przepisy na obiad i lunch',
    'Nisko-tłuszczowe przepisy z tuńczykiem',
    'Zdrowe i niskowęglowodanowe przepisy z tuńczykiem',
    'Wysokobiałkowe przepisy z jajkami',
    'Niskokaloryczne przepisy z jajami na utratę wagi',
    'Bezglutenowe przepisy z tuńczykiem',
  ],
  _id: '63a5a8ab9633a47ccc92dfb9',
};
